version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    expose:
      - 443
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - iantar
    depends_on:
      - wordpress
  

  wordpress:
    build: ./requirements/wordpress
    # image: php:8.2-fpm
    container_name: wordpress
    depends_on:
      - mariadb
    expose:
      - 9000
    networks:
      - iantar
    volumes:
      - wordpress_data:/var/www/wordpress
  

  mariadb:
    build: ./requirements/mariadb
    # image: php:8.2-fpm
    container_name: mariadb
    expose:
      - 3306
    networks:
      - iantar

    volumes:
      - mariadb_data:/var/lib/mysql
    # environment:
    #   - MYSQL_ROOT_PASSWORD=1234
  
networks:
  iantar:
    driver: bridge
volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local
