version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    expose:
      - 443
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - iantar
    depends_on:
      - wordpress
  

  wordpress:
    build: ./requirements/wordpress
    # image: php:8.2-fpm
    container_name: wordpress
    depends_on:
      - mariadb
    expose:
      - 9000
    networks:
      - iantar
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file:
      - .env
  

  mariadb:
    build: ./requirements/mariadb
    # image: php:8.2-fpm
    container_name: mariadb
    expose:
      - 3306
    networks:
      - iantar
    env_file:
      - .env

    volumes:
      - mariadb_data:/var/lib/mysql
    # environment:
    #   - MYSQL_ROOT_PASSWORD=1234


  static-website:
    build: ./requirements/bonus/static-website
    container_name: static-website
    expose:
      - 8000
    ports:
      - "8000:8000"

  
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    expose:
      - 8888
    ports:
      - "8888:8888"
    networks:
      - iantar

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    expose:
      - 6379
    networks:
      - iantar
  
  ftp-server:
    build: ./requirements/bonus/ftp-server
    container_name: ftp-server
    expose:
      - 20
      - 21
    volumes:
      - ftp-data:/var/www/wordpress
    networks:
      - iantar

  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    expose:
      - 8080
    ports:
      - "8080:8080"

networks:
  iantar:
    driver: bridge
volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local
  ftp-data:
    driver: local
